from __future__ import annotations

from cobra.models.cobra_model import COBRAModelConfig
from cobra.models.siglip_adapter import BackboneConfig


def build_model_config(config: dict) -> COBRAModelConfig:
    backbone_cfg = config["backbone"]
    model_cfg = config["model"]
    backbone = BackboneConfig(
        model_name=backbone_cfg["model_name"],
        pretrained=bool(backbone_cfg.get("pretrained", True)),
        image_size=int(backbone_cfg["image_size"]),
        embed_dim=int(backbone_cfg["embed_dim"]),
        patch_size=int(backbone_cfg["patch_size"]),
        adapter_dim=int(backbone_cfg["adapter_dim"]),
        adapter_dropout=float(backbone_cfg.get("adapter_dropout", 0.0)),
        model_dir=backbone_cfg.get("model_dir"),
        show_download_progress=bool(backbone_cfg.get("show_download_progress", True)),
        use_naflex=bool(backbone_cfg.get("use_naflex", False)),
        preferred_long_side=backbone_cfg.get("preferred_long_side"),
        max_num_patches=backbone_cfg.get("max_num_patches"),
    )
    return COBRAModelConfig(
        backbone=backbone,
        num_attribute_tokens=int(model_cfg["num_attribute_tokens"]),
        num_preference_tokens=int(model_cfg.get("num_preference_tokens", model_cfg["num_attribute_tokens"])),
        num_heads=int(model_cfg["num_heads"]),
        projection_dim=int(model_cfg["projection_dim"]),
        dropout=float(model_cfg.get("dropout", 0.0)),
        residual_scale=float(model_cfg.get("residual_scale", 1.0)),
        bridge_residual_scale=float(model_cfg.get("bridge_residual_scale", 1.0)),
        stage2_residual_prior=bool(model_cfg.get("stage2_residual_prior", True)),
        cross_attention_bridge=bool(model_cfg.get("cross_attention_bridge", True)),
        bridge_support_fit=bool(model_cfg.get("bridge_support_fit", False)),
        bridge_support_fit_ridge=float(model_cfg.get("bridge_support_fit_ridge", 0.05)),
        bridge_support_fit_shrinkage=float(model_cfg.get("bridge_support_fit_shrinkage", 20.0)),
        bridge_support_fit_max_abs_scale=float(model_cfg.get("bridge_support_fit_max_abs_scale", 1.5)),
        bridge_support_fit_detach=bool(model_cfg.get("bridge_support_fit_detach", True)),
        bridge_basis_fit=bool(model_cfg.get("bridge_basis_fit", False)),
        bridge_basis_fit_ridge=float(model_cfg.get("bridge_basis_fit_ridge", 0.08)),
        bridge_basis_fit_shrinkage=float(model_cfg.get("bridge_basis_fit_shrinkage", 12.0)),
        bridge_basis_fit_scale=float(model_cfg.get("bridge_basis_fit_scale", 0.0)),
        bridge_basis_fit_max_abs=model_cfg.get("bridge_basis_fit_max_abs"),
        bridge_basis_fit_detach=bool(model_cfg.get("bridge_basis_fit_detach", True)),
        support_residual_fusion=bool(model_cfg.get("support_residual_fusion", False)),
        support_residual_fusion_components=tuple(
            model_cfg.get(
                "support_residual_fusion_components",
                ("bridge", "bridge_basis", "retrieved", "kernel", "user_state"),
            )
        ),
        support_residual_fusion_ridge=float(model_cfg.get("support_residual_fusion_ridge", 0.15)),
        support_residual_fusion_shrinkage=float(model_cfg.get("support_residual_fusion_shrinkage", 12.0)),
        support_residual_fusion_max_abs_weight=float(model_cfg.get("support_residual_fusion_max_abs_weight", 2.0)),
        support_residual_fusion_min_support=int(model_cfg.get("support_residual_fusion_min_support", 50)),
        support_residual_fusion_validation_images=int(model_cfg.get("support_residual_fusion_validation_images", 20)),
        support_residual_fusion_validation_margin=float(model_cfg.get("support_residual_fusion_validation_margin", 0.0)),
        support_residual_fusion_validation_metric=str(model_cfg.get("support_residual_fusion_validation_metric", "residual_rank")),
        support_residual_fusion_detach=bool(model_cfg.get("support_residual_fusion_detach", True)),
        support_residual_score_fit=bool(model_cfg.get("support_residual_score_fit", False)),
        support_residual_score_fit_ridge=float(model_cfg.get("support_residual_score_fit_ridge", 0.05)),
        support_residual_score_fit_shrinkage=float(model_cfg.get("support_residual_score_fit_shrinkage", 8.0)),
        support_residual_score_fit_max_abs_scale=float(model_cfg.get("support_residual_score_fit_max_abs_scale", 2.0)),
        support_residual_score_fit_min_support=int(model_cfg.get("support_residual_score_fit_min_support", 50)),
        support_residual_score_fit_validation_images=int(model_cfg.get("support_residual_score_fit_validation_images", 0)),
        support_residual_score_fit_validation_margin=float(model_cfg.get("support_residual_score_fit_validation_margin", 0.0)),
        support_residual_score_fit_detach=bool(model_cfg.get("support_residual_score_fit_detach", True)),
        support_residual_score_fit_candidate_scales=tuple(
            float(scale) for scale in model_cfg.get("support_residual_score_fit_candidate_scales", ())
        ),
        piaa_token_fusion=bool(model_cfg.get("piaa_token_fusion", False)),
        piaa_token_fusion_tokens=int(model_cfg.get("piaa_token_fusion_tokens", 4)),
        piaa_token_fusion_min_support=int(model_cfg.get("piaa_token_fusion_min_support", 50)),
        piaa_token_fusion_scale=float(model_cfg.get("piaa_token_fusion_scale", 1.0)),
        piaa_token_fusion_detach=bool(model_cfg.get("piaa_token_fusion_detach", True)),
        piaa_token_fusion_mode=str(model_cfg.get("piaa_token_fusion_mode", "hard_topk")),
        piaa_token_fusion_temperature=float(model_cfg.get("piaa_token_fusion_temperature", 0.7)),
        residual_max=model_cfg.get("residual_max"),
        preference_mode=str(model_cfg.get("preference_mode", "hard")),
        preference_temperature=float(model_cfg.get("preference_temperature", 1.0)),
        score_bin_temperature=float(model_cfg.get("score_bin_temperature", 0.7)),
        preference_memory_source=str(model_cfg.get("preference_memory_source", "pooled")),
        preference_score_source=str(model_cfg.get("preference_score_source", "target")),
        base_score_source=str(model_cfg.get("base_score_source", "prior_stage1_delta")),
        stage1_delta_scale=float(model_cfg.get("stage1_delta_scale", 0.0)),
        direct_support_memory=bool(model_cfg.get("direct_support_memory", False)),
        direct_support_memory_tokens=int(model_cfg.get("direct_support_memory_tokens", 0)),
        direct_support_memory_loo_tokens=int(model_cfg.get("direct_support_memory_loo_tokens", 0)),
        direct_support_memory_scale=float(model_cfg.get("direct_support_memory_scale", 1.0)),
        query_support_memory_topk=int(model_cfg.get("query_support_memory_topk", 0)),
        query_support_memory_scale=float(model_cfg.get("query_support_memory_scale", 1.0)),
        stage2_token_adapter=bool(model_cfg.get("stage2_token_adapter", False)),
        stage2_token_adapter_hidden_dim=int(model_cfg.get("stage2_token_adapter_hidden_dim", 192)),
        stage2_token_adapter_dropout=float(model_cfg.get("stage2_token_adapter_dropout", 0.0)),
        stage2_token_adapter_scale=float(model_cfg.get("stage2_token_adapter_scale", 0.5)),
        support_encode_chunk_size=int(model_cfg.get("support_encode_chunk_size", 0)),
        support_calibration=bool(model_cfg.get("support_calibration", False)),
        calibration_hidden_dim=int(model_cfg.get("calibration_hidden_dim", 128)),
        calibration_dropout=float(model_cfg.get("calibration_dropout", 0.0)),
        calibration_residual_gate_center=float(model_cfg.get("calibration_residual_gate_center", 1.0)),
        calibration_residual_gate_range=float(model_cfg.get("calibration_residual_gate_range", 0.5)),
        support_residual_retrieval=bool(model_cfg.get("support_residual_retrieval", False)),
        support_residual_similarity_source=str(model_cfg.get("support_residual_similarity_source", "conditioned")),
        support_retrieval_temperature=float(model_cfg.get("support_retrieval_temperature", 0.2)),
        support_retrieval_scale=float(model_cfg.get("support_retrieval_scale", 0.0)),
        support_retrieval_detach=bool(model_cfg.get("support_retrieval_detach", True)),
        support_kernel_residual=bool(model_cfg.get("support_kernel_residual", False)),
        support_kernel_residual_temperature=float(model_cfg.get("support_kernel_residual_temperature", 0.03)),
        support_kernel_residual_ridge=float(model_cfg.get("support_kernel_residual_ridge", 0.1)),
        support_kernel_residual_scale=float(model_cfg.get("support_kernel_residual_scale", 0.0)),
        support_kernel_residual_shrinkage=float(model_cfg.get("support_kernel_residual_shrinkage", 0.0)),
        support_kernel_residual_max_abs=model_cfg.get("support_kernel_residual_max_abs"),
        support_kernel_residual_detach=bool(model_cfg.get("support_kernel_residual_detach", True)),
        linear_solve_device=str(model_cfg.get("linear_solve_device", "auto")),
        transductive_retrieval=bool(model_cfg.get("transductive_retrieval", False)),
        transductive_mode=str(model_cfg.get("transductive_mode", "iterative")),
        transductive_steps=int(model_cfg.get("transductive_steps", 0)),
        transductive_alpha=float(model_cfg.get("transductive_alpha", 0.85)),
        transductive_ridge=float(model_cfg.get("transductive_ridge", 1.0e-4)),
        transductive_topk=int(model_cfg.get("transductive_topk", 0)),
        tta_num_tokens=int(model_cfg.get("tta_num_tokens", 0)),
        tta_init_std=float(model_cfg.get("tta_init_std", 0.02)),
        tta_residual_log_scale_min=float(model_cfg.get("tta_residual_log_scale_min", -1.5)),
        tta_residual_log_scale_max=float(model_cfg.get("tta_residual_log_scale_max", 1.5)),
        tta_level_residual_log_scale_min=float(model_cfg.get("tta_level_residual_log_scale_min", -0.5)),
        tta_level_residual_log_scale_max=float(model_cfg.get("tta_level_residual_log_scale_max", 0.5)),
        tta_level_residual_bias_range=float(model_cfg.get("tta_level_residual_bias_range", 0.0)),
        residual_memory_levels=int(model_cfg.get("residual_memory_levels", 0)),
        residual_memory_temperature=float(model_cfg.get("residual_memory_temperature", 0.7)),
        residual_memory_confidence_tau=float(model_cfg.get("residual_memory_confidence_tau", 4.0)),
        residual_memory_min_confidence_scale=float(model_cfg.get("residual_memory_min_confidence_scale", 0.5)),
        semantic_prompt_memory=bool(model_cfg.get("semantic_prompt_memory", False)),
        semantic_prompts=tuple(model_cfg.get("semantic_prompts", ())),
        semantic_memory_tokens=int(model_cfg.get("semantic_memory_tokens", 0)),
        semantic_memory_temperature=float(model_cfg.get("semantic_memory_temperature", 0.07)),
        semantic_memory_scale=float(model_cfg.get("semantic_memory_scale", 0.2)),
        user_state_enabled=bool(model_cfg.get("user_state_enabled", False)),
        user_state_dim=int(model_cfg.get("user_state_dim", 32)),
        user_state_ridge=float(model_cfg.get("user_state_ridge", 0.1)),
        user_state_scale=float(model_cfg.get("user_state_scale", 0.2)),
        user_state_detach_support_residual=bool(model_cfg.get("user_state_detach_support_residual", True)),
    )
